site_name: "Documentation: simpleds"
theme: material
nav:
    - Overview: index.md
    - Installation: installation.md
    - Getting Started: getting-started.md
    - Docs:
        - simpleds.dstypes: interfaces/dstypes.md
        - simpleds.lp: interfaces/lp.md
        - simpleds.stats: interfaces/stats.md
        - simpleds.tables: interfaces/tables.md
    - Examples: examples.md
