site_name: "Documentation: simpleds"
theme: material
nav:
    - Overview: index.md
    - Installation: installation.md
    - Getting Started: getting-started.md
    - Docs:
        - simpleds.stats: interfaces/stats.md
    - Examples: examples.md
